<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class WhatsAppService
{
    protected string $apiUrl = 'http://localhost:8090/api/send-message';

    /**
     * Send a WhatsApp message.
     *
     * @param string $phone The phone number with country code.
     * @param string $message The message text to send.
     * @return bool True if successful, false otherwise.
     */
    public function sendMessage(string $phone, string $message): bool
    {
        // config() (not env()) so it survives `config:cache` — once config is cached, env()
        // returns null at runtime, which is what silently broke the bridge URL before.
        $bridgeEnabled = filter_var(config('services.whatsapp.bridge_enabled', false), FILTER_VALIDATE_BOOLEAN);

        // When the self-hosted bridge isn't enabled, local/dev has nothing on :8080 — the
        // call would hang and time out the OTP request. Skip it; the dev master code 000000
        // (see WhatsAppAuthController::verifyOtp) still lets you sign in.
        if (! $bridgeEnabled && app()->environment('local')) {
            Log::info("WhatsApp (local — not sent) to {$phone}: {$message}");
            return false;
        }

        $url = config('services.whatsapp.bridge_url', $this->apiUrl);

        try {
            $response = Http::connectTimeout(3)->timeout(20)->post($url, [
                'number' => $phone,
                'message' => $message,
            ]);

            if ($response->successful()) {
                return true;
            }

            Log::error('WhatsApp API Error: ' . $response->body());
            return false;
        } catch (\Exception $e) {
            Log::error('WhatsApp Service Exception: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Send a WhatsApp image (a QR generated by the bridge from $qrPayload) with a text caption.
     * Used to deliver the ticket QR + details on booking. Best-effort — returns false (logged)
     * if the bridge is unreachable or WhatsApp isn't linked yet.
     */
    public function sendMedia(string $phone, string $caption, string $qrPayload): bool
    {
        $bridgeEnabled = filter_var(config('services.whatsapp.bridge_enabled', false), FILTER_VALIDATE_BOOLEAN);

        if (! $bridgeEnabled && app()->environment('local')) {
            Log::info("WhatsApp media (local — not sent) to {$phone}: {$caption}");
            return false;
        }

        try {
            $response = Http::connectTimeout(3)->timeout(30)->post($this->bridgeBase() . '/api/send-media', [
                'number'  => $phone,
                'caption' => $caption,
                'qrData'  => $qrPayload,
            ]);

            if ($response->successful()) {
                return true;
            }

            Log::warning('WhatsApp media send failed: ' . $response->body());
            return false;
        } catch (\Exception $e) {
            Log::warning('WhatsApp media exception: ' . $e->getMessage());
            return false;
        }
    }

    /** Bridge origin (scheme+host+port), derived from the send-message URL or configured directly. */
    public function bridgeBase(): string
    {
        $base = config('services.whatsapp.bridge_base');
        if (is_string($base) && $base !== '') {
            return rtrim($base, '/');
        }

        // Fall back to stripping the path off the send-message URL.
        $url = (string) config('services.whatsapp.bridge_url', $this->apiUrl);
        $parts = parse_url($url);
        $scheme = $parts['scheme'] ?? 'http';
        $host = $parts['host'] ?? 'localhost';
        $port = isset($parts['port']) ? ':' . $parts['port'] : '';

        return "{$scheme}://{$host}{$port}";
    }
}
